name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: Инициализация рабочего процесса
        uses: actions/checkout@v3.3.0
      - name: Подготовка JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: corretto
      - name: Сборка и тестирование проекта
        uses: gradle/gradle-build-action@v2.4.0
        with:
          gradle-version: 8.0.2
          arguments: test
